services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: streamlit_service
    ports:
      - "8501:8501"
    volumes:
    - ./frontend:/app/frontend
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
